const Router = require('koa-router')
const hexoErrorHandler = require('../hexo/errorHandler')
const { validateRequestBody } = require('../util/middlewares')
const controller = require('./controller')
const router = new Router()
router.prefix('/install')
router.use(controller.checkInstalled)
router.get('/', controller.notInstalled)
router.post('/', hexoErrorHandler.notBlog, validateRequestBody(controller.v.install), controller.install)
router.post('/checkroot', hexoErrorHandler.notBlog, validateRequestBody(controller.v.root), controller.checkRoot)
module.exports = router
