import Router from "koa-router";
import { validateRequestBody } from "../util/middlewares.js";
import * as controller from "./controller.js";
const router = new Router();
router.post('/login', controller.basicAuth, controller.getToken);
router.post('/refresh', controller.jwtAuth, controller.blacklist, controller.requestRefreshToken, controller.getToken);
router.get('/info', controller.jwtAuth, controller.requestAccessToken, controller.info);
router.post('/logout', controller.jwtAuth, controller.requestAccessToken, controller.logout);
router.post('/password', controller.basicAuth, validateRequestBody(controller.v.password), controller.password);
export default router;
